#!/bin/bash

counter_one=1
counter_two=0
room=230
total=0
LD_LIBRARY_PATH=./expect5.45
echo > website.txt
echo $(date +%a" "%b" "%d" "%H:%M:%S) PDT XXXX
until [ $room -eq 260 ]; do


   # query for logged in students
   current_number=$(timeout 5 ./testSSH ${room} ${counter_two} ${counter_one} | wc -l)
   # use last command for more info 

   # check for a logged on user
   if [ $current_number -gt 1 ]; then
      
      let total=total+1

      # print computer number
      echo -n 1

   else echo -n 0
   fi

   # increment computer number
   let counter_one=counter_one+1


   # reset computer number back to what it was
   if [ $counter_one -eq 10 ]; then
      let counter_one=0
      let counter_two=counter_two+1
   fi
   
   # change the room number once all computers have been checked
   if [ $room -eq 220 ]; then

      #reset the counters and increment the room
      if [[ $counter_one -eq 1 && $counter_two -eq 3 ]]; then
         echo "Lab "$room": "$((30 - $total))" open<br>" >> website.txt
   	 echo
         let room=room+10
         let counter_one=1
         let total=0
         let counter_two=0
      fi

   elif [[ $room -gt 220 && $room -lt 270 ]]; then

      #reset the counters and increment the room
      if [[ $counter_one -eq 3 && $counter_two -eq 4 ]]; then
         echo "Lab "$room": "$((42 - $total))" open<br>" >> website.txt
         echo
         let room=room+10
         let counter_one=1
         let total=0
         let counter_two=0
      fi

   fi


done
echo "000000000000000000000000000000000000000000"
room=270
until [ $room -eq 280 ]; do


   # query for logged in students
   

   current_number=$(timeout 1 net rpc registry enumerate 'HKEY_USERS' -S acs-cseb${room}-${counter_two}${counter_one}.ucsd.edu -U 'AD\YOUR_USERNAME%A_PASSWORD' | grep Classes | wc -l)
   # use last command for more info 

   # check for a logged on user
   if [ $current_number -eq 2 ]; then
      
      let total=total+1

      # print computer number
      echo -n 1

   else echo -n 0
   fi

   # increment computer number
   let counter_one=counter_one+1


   # reset computer number back to what it was
   if [ $counter_one -eq 10 ]; then
      let counter_one=0
      let counter_two=counter_two+1
   fi
   

      #reset the counters and increment the room
      if [[ $counter_one -eq 9 && $counter_two -eq 4 ]]; then
         echo "Lab "$room": "$((42 - $total))" open<br>" >> website.txt
   	 echo
         let room=room+10
         let counter_one=1
         let total=0
         let counter_two=0
      fi


done
